---
- name: Create haproxy config/data dir
  ansible.builtin.file:
    path: /containers_vols/haproxy/certs
    owner: vagrant
    group: vagrant
    state: directory
    mode: '0755'

- name: Copy SSL certificate
  ansible.builtin.copy:
    src: files/local.pem
    dest: /containers_vols/haproxy/certs/local.pem
    owner: vagrant
    group: vagrant

- name: Copy haproxy.cfg
  ansible.builtin.template:
    src: templates/haproxy.cfg.j2
    dest: /containers_vols/haproxy/haproxy.cfg
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Pull HAProxy image
  containers.podman.podman_image:
    name: "{{ image_haproxy }}"
    pull: true

- name: Create HAProxy container
  containers.podman.podman_container:
    name: haproxy
    image: "{{ image_haproxy }}"
    volume:
      - '/containers_vols/haproxy/:/usr/local/etc/haproxy:z'
      - '/containers_vols/haproxy/certs/:/usr/local/etc/haproxy/certs:z'
    ports:
      - '8443:8443'
    state: started
